### ISSUE TITLE
capstone I - wireframes

### ISSUE THREAD

**Issue by mdewey** [juanxsalazar/assignments#19]
# It starts with a plan.

We are starting the final stretch of the cohort. This means we are starting to focus on our final projects.

When we go to start a new project. The first step is to create an elevator pitch. This is a short description that describes what your final project is doing. This should be similar to what you said during pitches.

The second step is to always plan out what we are doing. These early plans often take the shape of wireframes. This means that our first task for the capstone is to create our wireframes.

The elevator pitch and wire frames should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed but must be changed with purpose.

## Objectives

- Finalize the idea for your capstone
- Create wireframes for your capstone project
- Using `app-app to start implementing your HTML

## Requirements

- Using your favorite way to create wireframes (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are.
- Create a new repository for your capstone project

### Explorer Mode

- [x] Create the elevator pitch for your final projects.
- [x] Place this in the `README.md` of your capstone project repository

- [ ] Create a wireframe for each page in your page you capstone.
- [ ] Place these wireframes in a `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups, and prototypes.

**Comment by juanxsalazar** [comment]
I made a google docs to wireframe my idea and also just write down everything that I will eventually need for it. 
https://docs.google.com/document/d/1vwTP-ib9soSiZBwDbcy3mXu3EMnxzlqTt2Pa0PyvWgk/edit?usp=sharing
Here's my github to it.
https://github.com/juanxsalazar/jobs-near-you

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![That's what I'm talking abour](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--daadccdc1e457c3e96089eda8e8e0a03ba9022bc/xT9IgrBcGHHemEZ0Ws.gif)
> &ldquo;That's what I'm talking abour&rdquo;
__&mdash; via **[Venel](https://gifs.suncoast.io/venerations/9)**__
