### ISSUE TITLE
Week 01 - Day 4 - Mock Portoflio

### ISSUE THREAD

**Issue by mdewey** [juanxsalazar/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

Also, feel free to change it from Jason's picture to a picture of yourself.

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.
- [x] Make sure the site is responsive.
- [x] Deploy your site

### Adventure Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.

### Epic Mode
- [ ] Go back and work on the adventure or epic mode for a past assignment.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by juanxsalazar** [comment]
I didn't get a chance to finish the project, this is what I have currently have as of now. 
https://github.com/juanxsalazar/my-portfolio

**Comment by mdewey** [comment]
I would have liked to see more, but its good enough for me. Good job!

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/6)**__
