### ISSUE TITLE
Week 02  - Day 1 - Scoreboard

### ISSUE THREAD

**Issue by mdewey** [juanxsalazar/assignments#5]
# Score Board

For this assignment, you will be creating a simple interactive scoreboard for your favorite sport.

## Requirements

- Refer to this mockup to design your page:

![](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/fundamentals/javascript/assignments/assets/scoreboard.png)

- Use the HTML and CSS [here](https://gist.github.com/mdewey/d331c0a449b8e53b4adc472ec0e5a1e8) to jump-start your project.
- A user should be able to update a score and the teams playing.

### Explorer Mode

- [x] Create a new project and implement the design using the given HTML & CSS.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard-coded" value.
- [x] Deploy your site.

### Adventure Mode

- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its scoreboard (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

**Comment by juanxsalazar** [comment]
I was able to get the names changed and the counters working. I haven't figured out how to make the counter stop at 0 though and keep it from going to the negative numbers. If I figure out how to before midnight tonight, I'll commit it. 
https://github.com/juanxsalazar/scoreboard

**Comment by juanxsalazar** [comment]
I managed to finish explorer mode. I wasn't sure how to not have any negative numbers and ended up asking one of the alumni's for help and was told about if statements. Other then that, the most confusing part was figuring out the class names to put in the html based on javascript. That took me the longest to figure out. 
https://github.com/juanxsalazar/scoreboard

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
